services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=transaction_validator'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=user'
    ports:
      - '5432:5432'