spring:
  application:
    name: transaction-validator
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: ${spring.flyway.default-schema}
        jdbc.batch_size: 1000
        order_inserts: true
        query.fail_on_pagination_over_collection_fetch: true
  flyway:
    schemas: transaction_validator
    default-schema: transaction_validator
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/transaction_validator
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
